[package]
name = "wham"
version = "0.9.6"
authors = ["Daniel Bauer <bauer@cbs.tu-darmstadt.de>"]
description = "An implementation of the weighted histogram analysis method"
license = "GPL-3.0"
repository = "https://github.com/danijoo/WHAM"

[dependencies]
clap = {version="2.32.0", features=['yaml']}
error-chain = "0.12.0"
rand = "0.5.5"
rayon = "1.0.3"

[dev-dependencies]
assert_approx_eq = "1.1.0"

[profile.release]
opt-level = 2
